package com.mingrisoft.alarmclock.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mingrisoft.alarmclock.greendao.TimeEntity;

import com.mingrisoft.alarmclock.greendao.TimeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timeEntityDaoConfig;

    private final TimeEntityDao timeEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timeEntityDaoConfig = daoConfigMap.get(TimeEntityDao.class).clone();
        timeEntityDaoConfig.initIdentityScope(type);

        timeEntityDao = new TimeEntityDao(timeEntityDaoConfig, this);

        registerDao(TimeEntity.class, timeEntityDao);
    }
    
    public void clear() {
        timeEntityDaoConfig.getIdentityScope().clear();
    }

    public TimeEntityDao getTimeEntityDao() {
        return timeEntityDao;
    }

}
