package com.mingrisoft.alarmclock.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TIME_ENTITY".
 */
public class TimeEntity {

    private Long id;
    private Long ID;
    private String time;
    private String date;
    private Integer hour;
    private Integer min;
    private Boolean tf;

    public TimeEntity() {
    }

    public TimeEntity(Long id) {
        this.id = id;
    }

    public TimeEntity(Long id, Long ID, String time, String date, Integer hour, Integer min, Boolean tf) {
        this.id = id;
        this.ID = ID;
        this.time = time;
        this.date = date;
        this.hour = hour;
        this.min = min;
        this.tf = tf;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMin() {
        return min;
    }

    public void setMin(Integer min) {
        this.min = min;
    }

    public Boolean getTf() {
        return tf;
    }

    public void setTf(Boolean tf) {
        this.tf = tf;
    }

}
