package com.mingrisoft.setblacklist.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_ENTITY".
 */
public class PersonEntity {

    private Long id;
    private Long tag;
    private String UserName;
    private String Number;

    public PersonEntity() {
    }

    public PersonEntity(Long id) {
        this.id = id;
    }

    public PersonEntity(Long id, Long tag, String UserName, String Number) {
        this.id = id;
        this.tag = tag;
        this.UserName = UserName;
        this.Number = Number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTag() {
        return tag;
    }

    public void setTag(Long tag) {
        this.tag = tag;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getNumber() {
        return Number;
    }

    public void setNumber(String Number) {
        this.Number = Number;
    }

}
